### ISSUE TITLE
Contribute code in Python

### ISSUE THREAD

**Issue by SAY-droid427** [SAY-droid427/DSAQuestins#11]
Contributions for code in Python are welcome. Please mention the code you want to contribute.

**Comment by 96RadhikaJadhav** [comment]
@SAY-droid427  I can add different DSA solutions in python from hackerrank.

**Comment by SAY-droid427** [comment]
@96RadhikaJadhav Yes you may add DSA solutions. But for each different solution create separate pull requests.

**Comment by 96RadhikaJadhav** [comment]
@SAY-droid427 Sure.

**Comment by SAY-droid427** [comment]
@96RadhikaJadhav You have created a folder called SortingTechniques. Could you please create a folder named Python and move the sorting techniques into it

**Comment by um4ng-tiw** [comment]
> @96RadhikaJadhav You have created a folder called SortingTechniques. Could you please create a folder named Python and move the sorting techniques into it

I can do this and add more code for Python

**Comment by 96RadhikaJadhav** [comment]
@SAY-droid427  I moved SortingTechniques into Python folder. And also added radix sort program. Could you please check it.

**Comment by SAY-droid427** [comment]
@um4ng-tiw You can also add more code in Python
