### ISSUE TITLE
git clone fails

### ISSUE THREAD

**Issue by dwaipayan05** [SAY-droid427/DSAQuestins#36]
**Problem**
`git clone git@github.com:dwaipayan05/DSAQuestions.git` *fails*
`git clone git@github.com:SAY-droid427/DSAQuestions.git` *fails*

**Proposed Solution**
This is due to a invalid file-path error as mentioned in the SS below. Adding * in filenames causes such error. Please revoke the last commit and consider renaming `A*` to `A-Star`.

![image](https://user-images.githubusercontent.com/53687927/113399085-43c4b900-93bd-11eb-9d60-7281b5422462.png)

**Comment by SAY-droid427** [comment]
@dwaipayan05 Thank you for bringing this into my notice

**Comment by SAY-droid427** [comment]
@Dansmith-rgb Since this A* code was written by you could you please do the needful?

**Comment by dwaipayan05** [comment]
@SAY-droid427 I've reverted it as of now, I'll add it in my next PR with resources to README.md

**Comment by SAY-droid427** [comment]
@dwaipayan05 I have merged your PR, please add it in your next PR with the required changes.
