### ISSUE TITLE
Wanted to add Hackerrank folder

### ISSUE THREAD

**Issue by UG-SEP** [SAY-droid427/DSAQuestins#45]
Hey,
I wanted to add hackerrank solution folder where we can contribute our program 
I will add this inside [Solution Folder](https://github.com/SAY-droid427/DSAQuestions/tree/master/Solutions)
Please assign me

**Comment by SAY-droid427** [comment]
@UG-SEP Go ahead

**Comment by UG-SEP** [comment]
this issue has been solved
