### ISSUE TITLE
Discussion on methods to make the journey of learning to code more effective

### ISSUE THREAD

**Issue by SAY-droid427** [SAY-droid427/DSAQuestins#51]
This repository should not only be a culmination of data structures and algorithms but should also be a place for exchange of ideas to improve our learning methods in this awesome journey of coding. Please feel free to discuss how to make learning to code easier,  more enjoyable and more effective!

**Comment by SAY-droid427** [comment]
@dwaipayan05 @96RadhikaJadhav @UG-SEP @um4ng-tiw @Rishabh062  and others It would be great if you could start the discussion here as you guys have made a lot of contribution to this repository. Thank you!

**Comment by Rishabh062** [comment]
Thank you @SAY-droid427  for mentioning me. Sure I will start with the topic you mention. I also request other members to join this. 
Thanks you

**Comment by SAY-droid427** [comment]
I feel that coding becomes easier when involved in a community because a community becomes your inspiration and your support as you learn together and improve each day. For this reason, I have created a community "CodeHERS" for girls where they can come together and learn together. They can share their coding journey and inspire other women. This community will have the following features:
1. Teaching Git and Github to beginners 
2. Sharing resources for web development and app development
3. Competitive coding server for getting started in CP
4. Show and tell: Where girls will be able to share and showcase the projects they built, the challenges they faced and how they overcame it
Since we are just starting this community, collaborations are welcome and encouraged! 
Please share this with your female colleagues and ask them to join the Discord server:   https://discord.gg/m7MaGZMh

**Comment by dwaipayan05** [comment]
Please move this to [Github Discussions](https://docs.github.com/en/discussions)
